languageCode = "zh-cn"
languageName = "Simplified Chinese (China)"
displayName = "ZH-CN"
isoCode = "zh-cn"
weight = 1
rtl = false

title = "Blowfish"
logo = "img/blowfish_logo_transparent.png"
description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Banana1024"
  image = "img/blowfish_logo.png"
  headline = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  bio = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  # links = [
  #   { twitter = "https://twitter.com/burufugu" },
  #   { mastodon = "https://masto.ai/@blowfish" },
  #   { github = "https://github.com/nunocoracao/blowfish" },
  # ]
